<?php

return [

    // ──────────────────────────────────────────────
    //  SEEDS
    // ──────────────────────────────────────────────
    [
        'name'              => 'Anise Seeds',
        'slug'              => 'anise-seeds',
        'category'          => 'seeds',
        'image'             => 'seeds/anise_seeds.webp',
        'short_description' => 'Rich aroma and high anethole content. Carefully cleaned and sorted to export-grade specifications for tea, pharma and food markets.',
        'full_description'  => 'Egyptian anise seeds are globally prized for their rich, sweet aroma and exceptionally high anethole content. Sourced from prime Nile Delta growing regions, our anise undergoes rigorous multi-stage cleaning, gravity sorting and controlled drying to meet the exacting demands of spice blenders, herbal tea manufacturers and pharmaceutical producers worldwide.',
        'features'          => ['High Anethole Content', 'Multi-Stage Sorting', 'Low Moisture & Impurity', 'Export-Grade Quality'],
        'uses'              => ['Herbal teas & infusions', 'Spice blends & seasonings', 'Pharmaceutical & nutraceutical', 'Bakery & confectionery'],
        'origin'            => 'Egypt — Nile Delta Region',
        'form'              => 'Whole Seeds',
    ],
    [
        'name'              => 'Caraway',
        'slug'              => 'caraway',
        'category'          => 'seeds',
        'image'             => 'seeds/caraway.webp',
        'short_description' => 'Distinctive warm flavour and high oil yield. Supplied whole or ground for food manufacturing and seasoning applications.',
        'full_description'  => 'Egyptian caraway seeds deliver a warm, slightly peppery aroma and a naturally high carvone oil yield. Harvested from carefully selected farms and processed under strict hygiene protocols, our caraway meets the consistent quality standards required by European spice importers, food manufacturers and health product producers.',
        'features'          => ['High Carvone Oil Yield', 'Uniform Seed Size', 'Low Aflatoxin Levels', 'Whole or Ground Supply'],
        'uses'              => ['Bread & bakery products', 'Cheese & dairy flavouring', 'Liqueur & beverage production', 'Digestive health supplements'],
        'origin'            => 'Egypt — Upper Egypt Region',
        'form'              => 'Whole Seeds / Ground',
    ],
    [
        'name'              => 'Chia',
        'slug'              => 'chia',
        'category'          => 'seeds',
        'image'             => 'seeds/chia.webp',
        'short_description' => 'Nutrient-dense superfood seeds with high omega-3 and fibre content. Cleaned and sorted to food-grade export standards.',
        'full_description'  => 'Our export-grade chia seeds are cultivated under optimal growing conditions and processed through advanced cleaning and optical sorting systems to ensure exceptional purity. Rich in omega-3 fatty acids, dietary fibre and plant-based protein, they are supplied to health food brands, nutraceutical manufacturers and superfood retailers worldwide.',
        'features'          => ['High Omega-3 Content', 'Optical Sorting for Purity', 'Rich in Dietary Fibre', 'Non-GMO Certified'],
        'uses'              => ['Health food & functional snacks', 'Smoothies & beverages', 'Bakery & energy bars', 'Nutraceutical formulations'],
        'origin'            => 'Egypt',
        'form'              => 'Whole Seeds',
    ],
    [
        'name'              => 'Coriander',
        'slug'              => 'coriander',
        'category'          => 'seeds',
        'image'             => 'seeds/coriander.webp',
        'short_description' => 'Balanced lemon-spice aroma and high oil yield. Supplied whole or split year-round to spice blenders and food manufacturers.',
        'full_description'  => 'Egyptian coriander seeds are renowned for their balanced lemon-spice profile and consistently high essential oil content. Field-selected and processed to export specifications, they are supplied whole, split or ground to spice blenders, curry manufacturers and food producers across Europe, Asia and the Americas.',
        'features'          => ['High Essential Oil Yield', 'Balanced Aroma Profile', 'Whole or Split Supply', 'Consistent Batch Quality'],
        'uses'              => ['Curry blends & spice mixes', 'Pickling & marinades', 'Sausage & meat seasoning', 'Herbal tea blends'],
        'origin'            => 'Egypt — Nile Delta Region',
        'form'              => 'Whole / Split / Ground',
    ],
    [
        'name'              => 'Fennel Seeds',
        'slug'              => 'fennel-seeds',
        'category'          => 'seeds',
        'image'             => 'seeds/fennel seeds.webp',
        'short_description' => 'Sweet anise-like aroma with high anethole and fenchone content. A staple in tea, food and pharmaceutical markets.',
        'full_description'  => 'Egyptian fennel seeds are valued for their naturally sweet, anise-like aroma and high volatile oil content. Harvested from select farms and processed through multi-stage cleaning and drying, our fennel meets the strict purity and oil content specifications demanded by tea blenders, pharmaceutical producers and seasoning manufacturers globally.',
        'features'          => ['High Volatile Oil Content', 'Sweet Aroma Profile', 'Carefully Cleaned & Dried', 'Pharma & Food Grade'],
        'uses'              => ['Digestive herbal teas', 'Spice blends & seasonings', 'Baby food formulations', 'Pharmaceutical preparations'],
        'origin'            => 'Egypt — Nile Delta Region',
        'form'              => 'Whole Seeds',
    ],
    [
        'name'              => 'Fenugreek',
        'slug'              => 'fenugreek',
        'category'          => 'seeds',
        'image'             => 'seeds/fenugreek.webp',
        'short_description' => 'Consistent size, colour and low impurity levels. Trusted by spice brands, supplement producers and food manufacturers.',
        'full_description'  => 'High-quality Egyptian fenugreek seeds are sourced from verified farms and processed to maintain consistent seed size, uniform amber colour and low impurity levels. Widely used in curry blends, health supplements and traditional medicine, our fenugreek is a reliable, traceable supply for buyers across Europe, the Middle East and Asia.',
        'features'          => ['Consistent Size & Colour', 'Low Impurity Level', 'Traceable Farm Origin', 'Rich in Saponins'],
        'uses'              => ['Curry & spice blends', 'Health supplements', 'Dairy flavouring', 'Traditional medicine'],
        'origin'            => 'Egypt — Upper Egypt Region',
        'form'              => 'Whole Seeds / Powder',
    ],
    [
        'name'              => 'Flax Seed',
        'slug'              => 'flax-seed',
        'category'          => 'seeds',
        'image'             => 'seeds/flax seed.webp',
        'short_description' => 'Premium golden and brown flax seeds rich in omega-3 and lignans. Sorted and cleaned to strict export standards.',
        'full_description'  => 'Egyptian flax seeds are produced under controlled agricultural conditions and processed through advanced cleaning and gravity separation to guarantee purity and optimal oil content. Available in golden and brown varieties, our flax seed supplies health food producers, cold-press oil mills and functional food manufacturers with consistent, high-quality raw material.',
        'features'          => ['High Omega-3 Fatty Acids', 'Rich in Lignans', 'Golden & Brown Varieties', 'Cold-Press Oil Grade'],
        'uses'              => ['Cold-press linseed oil', 'Functional bakery products', 'Health & wellness supplements', 'Animal feed additive'],
        'origin'            => 'Egypt',
        'form'              => 'Whole Seeds / Cold-Press Oil Grade',
    ],
    [
        'name'              => 'Frik',
        'slug'              => 'frik',
        'category'          => 'seeds',
        'image'             => 'seeds/frik.webp',
        'short_description' => 'Young green durum wheat, fire-roasted for a distinctive smoky flavour. A traditional grain with growing global export demand.',
        'full_description'  => 'Frik (freekeh) is young green durum wheat harvested early and roasted over open fire to create its signature smoky, nutty flavour. Sourced from Egyptian farms and processed to remove impurities, our frik is supplied whole or cracked to specialty food importers, Middle Eastern grocers and health-conscious food brands seeking authentic grain products.',
        'features'          => ['Young Durum Wheat Grain', 'Distinctive Smoky Flavour', 'High Fibre & Protein', 'Whole or Cracked Form'],
        'uses'              => ['Traditional grain dishes', 'Specialty food retail', 'Restaurant & catering supply', 'Health food products'],
        'origin'            => 'Egypt',
        'form'              => 'Whole / Cracked',
    ],
    [
        'name'              => 'Lupina Seeds',
        'slug'              => 'lupina-seeds',
        'category'          => 'seeds',
        'image'             => 'seeds/lupina_seeds.webp',
        'short_description' => 'High-protein lupine beans with low bitterness after processing. Supplied to snack producers and plant-protein manufacturers.',
        'full_description'  => 'Egyptian lupina (lupin) seeds are high in plant protein and dietary fibre, making them a valued ingredient for health food and alternative protein markets. Our lupina is sourced from select farms, de-bittered through controlled water processing, and supplied to snack food manufacturers, plant-based protein producers and specialty food importers across Europe and the Middle East.',
        'features'          => ['High Plant Protein Content', 'Low Fat & High Fibre', 'Carefully De-Bittered', 'Gluten-Free Ingredient'],
        'uses'              => ['Plant-based protein products', 'Snack & street food', 'Lupin flour production', 'Animal feed supplement'],
        'origin'            => 'Egypt',
        'form'              => 'Whole Seeds / Dried',
    ],
    [
        'name'              => 'Sesame',
        'slug'              => 'sesame',
        'category'          => 'seeds',
        'image'             => 'seeds/sesame.webp',
        'short_description' => 'Premium white and natural sesame seeds with high oil content. Hulled or unhulled, sorted for colour and purity.',
        'full_description'  => 'Egyptian sesame seeds are among the finest in the global market, known for their high oil content, clean white colour and rich, nutty flavour. Processed through advanced optical colour sorting and multi-stage cleaning, our sesame is supplied hulled or unhulled to tahini producers, bakeries, confectioneries and oil extraction facilities worldwide.',
        'features'          => ['High Oil Content (50%+)', 'Optical Colour Sorting', 'Hulled & Unhulled Options', 'Low Free Fatty Acid'],
        'uses'              => ['Tahini & sesame oil production', 'Bakery & confectionery', 'Seasoning & bread topping', 'Health food & supplements'],
        'origin'            => 'Egypt — Upper Egypt Region',
        'form'              => 'Hulled / Natural Whole',
    ],
    [
        'name'              => 'White Beans',
        'slug'              => 'white-beans',
        'category'          => 'seeds',
        'image'             => 'seeds/white_beans.webp',
        'short_description' => 'Large, uniform white kidney beans with consistent colour and low impurity. Supplied to food manufacturers and retailers.',
        'full_description'  => 'Egyptian white beans (navy and cannellini varieties) are cultivated in fertile Nile Delta soils and processed through gravity sorting and colour separation to ensure uniform size, bright colour and minimal impurities. Supplied to canned food manufacturers, dry grocery retailers and food service companies requiring a reliable, consistent source of premium legumes.',
        'features'          => ['Uniform Size & Bright Colour', 'Low Impurity Level', 'High Protein & Fibre', 'Multiple Variety Options'],
        'uses'              => ['Canned & processed foods', 'Dry grocery retail', 'Soup & stew production', 'Food service supply'],
        'origin'            => 'Egypt — Nile Delta Region',
        'form'              => 'Dried Whole Beans',
    ],

    // ──────────────────────────────────────────────
    //  HERBS
    // ──────────────────────────────────────────────
    [
        'name'              => 'Basil',
        'slug'              => 'basil',
        'category'          => 'herbs',
        'image'             => 'herbs_images/basil.webp',
        'short_description' => 'Sweet, aromatic dried basil with vibrant colour and high essential oil content. Ideal for culinary and flavouring applications.',
        'full_description'  => 'Egyptian dried basil is harvested at peak maturity to capture maximum essential oil content and characteristic sweet-spicy aroma. Processed through gentle drying and cleaning, our basil is supplied as whole leaf, cut & sifted or powder to food manufacturers, seasoning blenders and herb importers seeking consistent flavour and colour.',
        'features'          => ['Harvested at Peak Maturity', 'High Essential Oil Content', 'Vibrant Green Colour', 'Whole Leaf or C&S Grade'],
        'uses'              => ['Pasta sauces & Italian cuisine', 'Spice blends & seasonings', 'Herbal teas & infusions', 'Natural flavouring'],
        'origin'            => 'Egypt',
        'form'              => 'Whole Leaf / Cut & Sifted / Powder',
    ],
    [
        'name'              => 'Bay Leaves',
        'slug'              => 'bay-leaves',
        'category'          => 'herbs',
        'image'             => 'herbs_images/bay_leaves.webp',
        'short_description' => 'Aromatic dried bay leaves with strong, complex flavour. Supplied whole or broken to food producers worldwide.',
        'full_description'  => 'Egyptian bay leaves are hand-selected and naturally dried to preserve their distinctive aromatic oils and complex flavour profile. Supplied whole, broken or as an extract, our bay leaves serve food manufacturers, soup and stock producers, and spice blenders who require consistent fragrance and flavour in every batch.',
        'features'          => ['Hand-Selected Leaves', 'Strong Aromatic Profile', 'Naturally Sun-Dried', 'Whole or Broken Grade'],
        'uses'              => ['Soups, stews & stocks', 'Pickling & marinades', 'Spice blends', 'Essential oil extraction'],
        'origin'            => 'Egypt',
        'form'              => 'Whole / Broken',
    ],
    [
        'name'              => 'Calendula',
        'slug'              => 'calendula',
        'category'          => 'herbs',
        'image'             => 'herbs_images/calendula.webp',
        'short_description' => 'Vibrant orange petals rich in carotenoids and flavonoids. Used in cosmetics, herbal tea and pharmaceutical applications.',
        'full_description'  => 'Egyptian calendula flowers are harvested at full bloom to capture peak carotenoid and flavonoid content. Carefully dried to maintain their vivid orange colour and therapeutic properties, our calendula is supplied as whole flowers or petals to cosmetic manufacturers, herbal tea blenders and natural health product companies.',
        'features'          => ['High Carotenoid Content', 'Vibrant Orange Colour Retention', 'Whole Flower or Petals', 'Cosmetic & Pharma Grade'],
        'uses'              => ['Skincare & cosmetic formulations', 'Herbal & wellness teas', 'Natural food colouring', 'Pharmaceutical preparations'],
        'origin'            => 'Egypt',
        'form'              => 'Whole Flowers / Petals',
    ],
    [
        'name'              => 'Chamomile',
        'slug'              => 'chamomile',
        'category'          => 'herbs',
        'image'             => 'herbs_images/chamomile.webp',
        'short_description' => 'Premium flowers with high volatile oil, bright colour and characteristic aroma. Meets pharma and herbal tea market requirements.',
        'full_description'  => 'Egyptian chamomile is among the world\'s most sought-after, valued for its high volatile oil content, uniform flower head size and characteristic apple-like aroma. Harvested and dried under controlled conditions, our chamomile meets the stringent requirements of pharmaceutical buyers, premium herbal tea brands and cosmetic ingredient suppliers.',
        'features'          => ['High Volatile Oil Content', 'Uniform Flower Size', 'Low Moisture Content', 'Pharma & Tea Grade'],
        'uses'              => ['Premium herbal tea blends', 'Pharmaceutical preparations', 'Cosmetic & skincare products', 'Natural flavouring'],
        'origin'            => 'Egypt — Nile Delta Region',
        'form'              => 'Whole Flowers / Extract',
    ],
    [
        'name'              => 'Dill',
        'slug'              => 'dill',
        'category'          => 'herbs',
        'image'             => 'herbs_images/dill.webp',
        'short_description' => 'Fragrant dried dill herb and seeds with a fresh, slightly tangy aroma. Widely used in European and Middle Eastern cuisine.',
        'full_description'  => 'Egyptian dried dill weed and dill seeds offer a fresh, slightly tangy-anise aroma that is valued by European and Middle Eastern food producers. Harvested at optimal stage and processed to maintain flavour integrity, our dill is supplied to pickle manufacturers, seafood processors, spice blenders and herbal supplement companies.',
        'features'          => ['Fresh Tangy Aroma', 'Herb or Seed Form', 'Low Stem Content', 'Consistent Flavour Batch to Batch'],
        'uses'              => ['Pickling & brining', 'Seafood & fish seasoning', 'Dressings & sauces', 'Spice blends'],
        'origin'            => 'Egypt',
        'form'              => 'Dried Weed / Whole Seeds',
    ],
    [
        'name'              => 'Dried Molokhia',
        'slug'              => 'dried-molokhia',
        'category'          => 'herbs',
        'image'             => 'herbs_images/dried_molokhia.webp',
        'short_description' => 'Tender dried jute leaves with vivid green colour and high nutritional value. A staple herb in Middle Eastern and African markets.',
        'full_description'  => 'Molokhia (jute mallow) is a nutritionally rich leafy herb deeply rooted in Egyptian culinary tradition. Our dried molokhia is harvested young for tenderness, gently dried to preserve its vivid green colour and high iron, calcium and vitamin content, and supplied to Middle Eastern food manufacturers, ethnic grocery distributors and health food importers.',
        'features'          => ['Young Tender Leaves', 'Vibrant Green Colour', 'High Iron & Calcium', 'Authentic Egyptian Origin'],
        'uses'              => ['Traditional Middle Eastern dishes', 'Ethnic food manufacturing', 'Nutritional supplement ingredient', 'Specialty grocery retail'],
        'origin'            => 'Egypt',
        'form'              => 'Dried Whole / Crushed Leaf',
    ],
    [
        'name'              => 'Dried Sage',
        'slug'              => 'dried-sage',
        'category'          => 'herbs',
        'image'             => 'herbs_images/dried_sage.webp',
        'short_description' => 'Earthy, slightly peppery dried sage with strong aromatic oils. Used in culinary, pharmaceutical and cosmetic applications.',
        'full_description'  => 'Egyptian dried sage is harvested from robust plants cultivated in well-drained soils and dried under controlled low-heat conditions to preserve its high thujone and camphor content. Supplied as rubbed sage, cut & sifted or powder, it is sourced by seasoning manufacturers, pharmaceutical companies and aromatherapy product producers.',
        'features'          => ['High Thujone Content', 'Earthy Aromatic Profile', 'Rubbed, C&S or Powder', 'Low Moisture Retention'],
        'uses'              => ['Poultry & meat seasoning', 'Pharmaceutical preparations', 'Aromatherapy & essential oils', 'Herbal tea blends'],
        'origin'            => 'Egypt',
        'form'              => 'Rubbed / Cut & Sifted / Powder',
    ],
    [
        'name'              => 'Henna',
        'slug'              => 'henna',
        'category'          => 'herbs',
        'image'             => 'herbs_images/henna.webp',
        'short_description' => 'Pure dried henna leaf powder with high lawsone content. Supplied to cosmetic, hair care and natural dye manufacturers.',
        'full_description'  => 'Egyptian henna (Lawsonia inermis) is cultivated in Upper Egypt\'s warm dry climate, which produces leaves with naturally high lawsone content — the active dyeing compound. Our henna is finely milled under strict hygiene conditions and supplied pure and additive-free to cosmetic manufacturers, hair care brands, natural textile dye producers and traditional body art suppliers globally.',
        'features'          => ['High Lawsone Content', 'Pure & Additive-Free', 'Fine Particle Milling', 'Cosmetic & Hair Grade'],
        'uses'              => ['Natural hair colouring', 'Body art & tattoo paste', 'Natural textile dyeing', 'Cosmetic formulations'],
        'origin'            => 'Egypt — Upper Egypt (Aswan Region)',
        'form'              => 'Fine Powder',
    ],
    [
        'name'              => 'Hibiscus',
        'slug'              => 'hibiscus',
        'category'          => 'herbs',
        'image'             => 'herbs_images/hibiscus.webp',
        'short_description' => 'Deep crimson petals with high anthocyanin content and a tart, cranberry-like flavour. A premium ingredient for beverages and health products.',
        'full_description'  => 'Egyptian hibiscus (Roselle / Hibiscus sabdariffa) is globally regarded as among the finest, with deep crimson calyces, high anthocyanin content and a vibrant tart flavour. Harvested at full maturity and dried under controlled conditions, our hibiscus supplies premium tea brands, natural colouring manufacturers, pharmaceutical companies and functional beverage producers worldwide.',
        'features'          => ['High Anthocyanin Content', 'Deep Crimson Colour', 'Naturally Tart Flavour', 'Whole Calyces or Cut'],
        'uses'              => ['Herbal & wellness teas', 'Natural food & beverage colouring', 'Functional drink formulations', 'Pharmaceutical antioxidant ingredient'],
        'origin'            => 'Egypt — Upper Egypt Region',
        'form'              => 'Whole Calyces / Cut & Sifted / Powder',
    ],
    [
        'name'              => 'Lemongrass',
        'slug'              => 'lemongrass',
        'category'          => 'herbs',
        'image'             => 'herbs_images/lemon_grass.webp',
        'short_description' => 'Fragrant dried lemongrass with fresh citrus-like aroma and high citral content. Ideal for beverages, food and aromatherapy.',
        'full_description'  => 'Egyptian lemongrass is cultivated in warm growing regions and processed at optimal maturity to capture its naturally high citral content and fresh, lemony aroma. Supplied as cut stalks, dried flakes or essential oil-grade material, our lemongrass serves herbal tea manufacturers, food flavouring companies and essential oil distillers.',
        'features'          => ['High Citral Content', 'Fresh Citrus Aroma', 'Cut Stalk or Dried Flake', 'Essential Oil Grade Available'],
        'uses'              => ['Herbal tea & infusions', 'Asian cuisine flavouring', 'Essential oil distillation', 'Cosmetic & aromatherapy products'],
        'origin'            => 'Egypt',
        'form'              => 'Cut Stalks / Dried Flakes',
    ],
    [
        'name'              => 'Liquorice',
        'slug'              => 'liquorice',
        'category'          => 'herbs',
        'image'             => 'herbs_images/liquorice.webp',
        'short_description' => 'Egyptian liquorice root with high glycyrrhizin content. Widely used in confectionery, pharmaceutical and tobacco industries.',
        'full_description'  => 'Egyptian liquorice root (Glycyrrhiza glabra) is one of the most commercially important herbal exports from Egypt, with naturally high glycyrrhizin content that delivers its characteristic sweet flavour. Supplied as dried root, extract or powder, our liquorice serves global confectionery manufacturers, pharmaceutical producers, tobacco flavourists and herbal supplement companies.',
        'features'          => ['High Glycyrrhizin Content', 'Sweet, Clean Flavour Profile', 'Root, Extract or Powder Form', 'Pharma & Food Grade'],
        'uses'              => ['Confectionery & candy production', 'Pharmaceutical preparations', 'Tobacco flavouring', 'Herbal supplements & tea'],
        'origin'            => 'Egypt — Upper Egypt',
        'form'              => 'Dried Root / Extract / Powder',
    ],
    [
        'name'              => 'Marjoram',
        'slug'              => 'marjoram',
        'category'          => 'herbs',
        'image'             => 'herbs_images/marjoram.webp',
        'short_description' => 'Mild, sweet-oregano flavoured herb with high essential oil. A versatile culinary and pharmaceutical ingredient.',
        'full_description'  => 'Egyptian marjoram is one of the country\'s most valuable herb exports, prized for its mild, sweet-oregano aroma and high terpinene-4-ol and sabinene content. Harvested at peak flowering stage and dried under controlled conditions, our marjoram is supplied to European spice manufacturers, pharmaceutical companies and herbal tea blenders as a reliable, traceable raw material.',
        'features'          => ['High Terpinene-4-ol Content', 'Mild Sweet-Oregano Aroma', 'Harvested at Peak Flowering', 'C&S or Powder Grade'],
        'uses'              => ['Meat & poultry seasoning', 'Mediterranean spice blends', 'Herbal tea formulations', 'Pharmaceutical & cosmetic industry'],
        'origin'            => 'Egypt — Nile Delta Region',
        'form'              => 'Dried Whole / Cut & Sifted / Powder',
    ],
    [
        'name'              => 'Moringa',
        'slug'              => 'moringa',
        'category'          => 'herbs',
        'image'             => 'herbs_images/moringa.webp',
        'short_description' => 'Nutrient-dense moringa leaf powder with exceptional vitamin and mineral profile. The "miracle tree" in superfood and supplement markets.',
        'full_description'  => 'Egyptian moringa (Moringa oleifera) leaves are harvested young, shade-dried at low temperature and milled to a fine powder to preserve their exceptional nutritional profile — rich in vitamins A, C and E, iron, calcium and plant-based protein. Supplied to health supplement brands, functional food manufacturers and wellness product companies globally.',
        'features'          => ['Shade-Dried at Low Temp', 'High Vitamins A, C & E', 'Rich in Iron & Calcium', 'Superfood Grade Powder'],
        'uses'              => ['Nutritional supplements & capsules', 'Superfood powders & smoothies', 'Functional food fortification', 'Cosmetic & skincare applications'],
        'origin'            => 'Egypt',
        'form'              => 'Dried Leaf / Fine Powder',
    ],
    [
        'name'              => 'Parsley',
        'slug'              => 'parsley',
        'category'          => 'herbs',
        'image'             => 'herbs_images/parsley.webp',
        'short_description' => 'Bright green dried parsley with clean, fresh flavour. Supplied as flakes or powder to food manufacturers and spice blenders.',
        'full_description'  => 'Egyptian dried parsley is produced from curly and flat-leaf varieties harvested at optimal stage and dried under controlled conditions to retain vivid green colour and fresh herbal flavour. Supplied as flakes or powder to spice manufacturers, food processors, seasoning blenders and ready-meal producers requiring consistent colour and flavour in every consignment.',
        'features'          => ['Vivid Green Colour Retention', 'Fresh Herbal Flavour', 'Flake or Powder Form', 'Consistent Batch Quality'],
        'uses'              => ['Spice blends & seasonings', 'Ready meals & food processing', 'Dried herb retail', 'Soup & sauce production'],
        'origin'            => 'Egypt',
        'form'              => 'Dried Flakes / Powder',
    ],
    [
        'name'              => 'Rosemary',
        'slug'              => 'rosemary',
        'category'          => 'herbs',
        'image'             => 'herbs_images/rosemary.webp',
        'short_description' => 'Strongly aromatic dried rosemary with high antioxidant and rosmarinic acid content. A premium culinary and industrial herb.',
        'full_description'  => 'Egyptian dried rosemary offers an intensely aromatic, pine-like fragrance with high rosmarinic acid and carnosic acid content — both valued for their natural antioxidant properties. Supplied as whole sprigs, cut & sifted or rosemary extract to food manufacturers, natural antioxidant producers, cosmetic companies and seasoning blenders worldwide.',
        'features'          => ['High Rosmarinic Acid Content', 'Natural Antioxidant Properties', 'Pine-Like Intense Aroma', 'Whole, C&S or Extract'],
        'uses'              => ['Meat & poultry seasoning', 'Natural food antioxidant', 'Cosmetic & personal care', 'Essential oil production'],
        'origin'            => 'Egypt',
        'form'              => 'Whole Sprigs / Cut & Sifted / Extract',
    ],
    [
        'name'              => 'Spearmint',
        'slug'              => 'spearmint',
        'category'          => 'herbs',
        'image'             => 'herbs_images/spearmint.webp',
        'short_description' => 'Deep green leaves with a milder, sweeter mint character and high carvone content. Preferred for beverages and confectionery.',
        'full_description'  => 'Egyptian spearmint is cultivated in prime Nile Delta growing areas and harvested at peak essential oil content to deliver its characteristically mild, sweet mint profile. With naturally high carvone and lower menthol than peppermint, it is the preferred mint variety for beverages, chewing gum, oral care products and Middle Eastern culinary use.',
        'features'          => ['High Carvone Content', 'Mild Sweet Mint Character', 'Deep Green Leaf Colour', 'Low Stem & Dust'],
        'uses'              => ['Beverages & flavoured water', 'Chewing gum & confectionery', 'Oral care products', 'Herbal tea blends'],
        'origin'            => 'Egypt — Nile Delta Region',
        'form'              => 'Dried Leaf / Cut & Sifted / Essential Oil',
    ],
    [
        'name'              => 'Thyme',
        'slug'              => 'thyme',
        'category'          => 'herbs',
        'image'             => 'herbs_images/thyme.webp',
        'short_description' => 'Highly aromatic dried thyme with strong thymol content. A versatile herb for culinary, pharmaceutical and cosmetic industries.',
        'full_description'  => 'Egyptian dried thyme is harvested from robust plants cultivated in well-drained soils and dried at controlled temperature to preserve high thymol content and strong aromatic character. Widely supplied to food manufacturers, pharmaceutical producers, cosmetic ingredient companies and spice blenders who require consistent potency and microbiological safety in every lot.',
        'features'          => ['High Thymol Content', 'Strong Aromatic Character', 'Pharmaceutical Grade Available', 'Whole Leaf or Powder'],
        'uses'              => ['Culinary seasoning blends', 'Antimicrobial pharmaceutical use', 'Cosmetic & personal care', 'Herbal & wellness teas'],
        'origin'            => 'Egypt',
        'form'              => 'Dried Whole Leaf / Powder',
    ],

    // ──────────────────────────────────────────────
    //  SPICES
    // ──────────────────────────────────────────────
    [
        'name'              => 'Black Pepper',
        'slug'              => 'black-pepper',
        'category'          => 'spices',
        'image'             => 'spices/black_papper.webp',
        'short_description' => 'Bold heat and piperine-rich whole peppercorns. Supplied whole or ground to food manufacturers and spice blenders globally.',
        'full_description'  => 'Our export-grade black pepper is sourced from prime growing regions and processed through multi-stage cleaning, sorting and drying to guarantee consistent piperine content, low moisture and minimal impurities. Supplied as whole peppercorns, cracked or finely ground to spice blenders, food manufacturers, hotel chains and retail packagers worldwide.',
        'features'          => ['High Piperine Content', 'Multi-Stage Sorting', 'Whole, Cracked or Ground', 'Low Moisture Content'],
        'uses'              => ['Spice blends & rubs', 'Processed meat & poultry', 'Restaurant & food service', 'Retail spice packaging'],
        'origin'            => 'Egypt (sourced & processed)',
        'form'              => 'Whole / Cracked / Ground',
    ],
    [
        'name'              => 'Cardamom',
        'slug'              => 'cardamom',
        'category'          => 'spices',
        'image'             => 'spices/cardamom.webp',
        'short_description' => 'Intensely aromatic pods and seeds with high 1,8-cineole content. A premium spice for beverages, confectionery and perfumery.',
        'full_description'  => 'Premium cardamom pods and seeds with an intense, complex aroma profile driven by naturally high 1,8-cineole content. Processed under strict hygiene conditions to preserve volatile oils, our cardamom is supplied to Middle Eastern beverage producers, high-end confectionery manufacturers, perfumers and spice blenders seeking a consistent, traceable source.',
        'features'          => ['High 1,8-Cineole Content', 'Intense Complex Aroma', 'Pods or Decorticated Seeds', 'Pharma & Beverage Grade'],
        'uses'              => ['Arabic & Turkish coffee', 'Confectionery & pastries', 'Masala chai blends', 'Perfumery & flavouring'],
        'origin'            => 'Egypt (sourced & processed)',
        'form'              => 'Whole Pods / Decorticated Seeds / Ground',
    ],
    [
        'name'              => 'Chili',
        'slug'              => 'chili',
        'category'          => 'spices',
        'image'             => 'spices/chili.webp',
        'short_description' => 'High-pungency dried chili with consistent Scoville rating. Supplied whole or ground to food manufacturers and sauce producers.',
        'full_description'  => 'Egyptian dried chili is processed from varieties selected for their consistent heat level, bright colour and high capsaicin content. Cleaned, dried and sorted to remove foreign matter and mould, our chili is supplied to hot sauce producers, food processors, spice blenders and meat seasoning manufacturers requiring a reliably pungent ingredient.',
        'features'          => ['Consistent Scoville Rating', 'High Capsaicin Content', 'Bright Red Colour', 'Whole or Ground Form'],
        'uses'              => ['Hot sauces & condiments', 'Spice blends & rubs', 'Processed food seasoning', 'Snack flavouring'],
        'origin'            => 'Egypt',
        'form'              => 'Whole / Flakes / Ground',
    ],
    [
        'name'              => 'Chili Peppers',
        'slug'              => 'chili-peppers',
        'category'          => 'spices',
        'image'             => 'spices/chili_paper.webp',
        'short_description' => 'Whole and sliced dried red chili peppers with vibrant colour and bold heat. Used in culinary and industrial food applications.',
        'full_description'  => 'Our dried chili peppers are harvested at full red maturity and processed through hygienically controlled drying and cleaning to maintain their vibrant red colour, bold capsaicin heat and rich flavour. Available as whole pods, rings or coarse flakes, they are supplied to ethnic food manufacturers, culinary distributors and spice importers globally.',
        'features'          => ['Harvested at Full Red Maturity', 'Bold Heat & Rich Flavour', 'Whole, Rings or Flakes', 'Vivid Colour Retention'],
        'uses'              => ['Ethnic & Asian cuisine', 'Chili oil & infused oils', 'Food manufacturing', 'Specialty retail & food service'],
        'origin'            => 'Egypt',
        'form'              => 'Whole / Rings / Coarse Flakes',
    ],
    [
        'name'              => 'Cinnamon Stick',
        'slug'              => 'cinnamon-stick',
        'category'          => 'spices',
        'image'             => 'spices/cinamon_stick.webp',
        'short_description' => 'Warm, sweet cinnamon quills with high cinnamaldehyde content. Supplied as sticks, broken or ground for food and beverage applications.',
        'full_description'  => 'Our cinnamon sticks are sourced from Ceylon and Cassia varieties, processed and graded for consistent diameter, tightly rolled quills and high cinnamaldehyde content. Supplied as whole sticks, broken quills or finely ground powder to beverage manufacturers, bakeries, confectioneries, functional food companies and spice retailers.',
        'features'          => ['High Cinnamaldehyde Content', 'Tightly Rolled Quills', 'Ceylon & Cassia Varieties', 'Whole, Broken or Ground'],
        'uses'              => ['Baking & confectionery', 'Hot beverages & mulled drinks', 'Curry blends & spice mixes', 'Functional health products'],
        'origin'            => 'Egypt (processed & exported)',
        'form'              => 'Whole Sticks / Broken / Ground',
    ],
    [
        'name'              => 'Clove',
        'slug'              => 'clove',
        'category'          => 'spices',
        'image'             => 'spices/clove.webp',
        'short_description' => 'Intensely aromatic whole cloves with high eugenol content. Used in food, pharmaceutical and dental product manufacturing.',
        'full_description'  => 'Premium dried clove buds with a naturally high eugenol content, delivering an intense, warm-spicy aroma that is valued across food, pharmaceutical and cosmetic industries. Supplied whole or ground to spice blenders, confectionery manufacturers, dental product producers and essential oil distillers requiring a consistently potent, clean raw material.',
        'features'          => ['High Eugenol Content (70%+)', 'Intense Warm-Spicy Aroma', 'Whole Bud or Ground', 'Dental & Pharmaceutical Grade'],
        'uses'              => ['Spice blends & seasonings', 'Dental & oral care products', 'Eugenol essential oil production', 'Confectionery & baked goods'],
        'origin'            => 'Egypt (processed & exported)',
        'form'              => 'Whole Buds / Ground',
    ],
    [
        'name'              => 'Cumin',
        'slug'              => 'cumin',
        'category'          => 'spices',
        'image'             => 'spices/cumin.webp',
        'short_description' => 'Earthy, warm dried cumin seeds and powder with high cuminaldehyde content. A cornerstone spice for global food manufacturing.',
        'full_description'  => 'Egyptian cumin seeds are recognized globally for their rich, earthy aroma and high cuminaldehyde content. Cleaned through multi-stage gravity and optical sorting, dried to optimal moisture and supplied as whole seeds or finely ground powder to curry manufacturers, seasoning blenders, food processors and spice retailers across Europe, Asia and the Americas.',
        'features'          => ['High Cuminaldehyde Content', 'Earthy Rich Aroma', 'Whole Seeds or Fine Powder', 'Multi-Stage Sorted'],
        'uses'              => ['Curry blends & spice mixes', 'Meat & poultry seasoning', 'Hummus & dip production', 'Ethnic food manufacturing'],
        'origin'            => 'Egypt',
        'form'              => 'Whole Seeds / Ground Powder',
    ],
    [
        'name'              => 'Dried Black Lemon',
        'slug'              => 'dried-black-lemon',
        'category'          => 'spices',
        'image'             => 'spices/dried_black_lemon.webp',
        'short_description' => 'Sun-dried limes with a complex sour-smoky flavour. A unique Middle Eastern spice used in stews, marinades and spice blends.',
        'full_description'  => 'Dried black lemon (loomi) is made from whole limes that are boiled in salt water and sun-dried until they turn hard and black, developing a unique sour, tangy and slightly smoky flavour profile. A cornerstone ingredient in Gulf and Middle Eastern cuisine, our dried black lemons are supplied whole, broken or ground to ethnic food manufacturers, specialty food importers and culinary distributors.',
        'features'          => ['Unique Sour-Smoky Profile', 'Sun-Dried Traditional Process', 'Whole, Broken or Ground', 'Authentic Middle Eastern Origin'],
        'uses'              => ['Gulf & Middle Eastern stews', 'Spice blend ingredient', 'Marinades & rice dishes', 'Specialty food retail'],
        'origin'            => 'Egypt',
        'form'              => 'Whole / Broken / Ground',
    ],
    [
        'name'              => 'Dried Garlic',
        'slug'              => 'dried-garlic',
        'category'          => 'spices',
        'image'             => 'spices/dried_garlic.webp',
        'short_description' => 'Pungent dried garlic granules, flakes and powder with consistent allicin potential. A staple ingredient for food manufacturers worldwide.',
        'full_description'  => 'Egyptian dried garlic is produced from selected high-pungency varieties, peeled, sliced or minced and dehydrated under controlled conditions to preserve allicin potential and characteristic sharp garlic flavour. Supplied as granules, flakes or fine powder to food processors, seasoning manufacturers, snack producers and restaurant supply chains worldwide.',
        'features'          => ['High Allicin Potential', 'Sharp Consistent Flavour', 'Granules, Flakes or Powder', 'Peeled & Dehydrated'],
        'uses'              => ['Seasoning blends & rubs', 'Processed food & snacks', 'Ready meal manufacturing', 'Garlic bread & sauces'],
        'origin'            => 'Egypt',
        'form'              => 'Granules / Flakes / Powder',
    ],
    [
        'name'              => 'Dried Onion Slices',
        'slug'              => 'dried-onion-slices',
        'category'          => 'spices',
        'image'             => 'spices/dried_onion_slice.webp',
        'short_description' => 'Dehydrated onion rings, flakes and powder with strong, consistent flavour. Widely used in processed food and seasoning production.',
        'full_description'  => 'Egyptian dehydrated onion products are made from large, high-solid white and yellow onion varieties, sliced uniformly and dehydrated under controlled conditions to maintain flavour intensity and natural colour. Supplied as rings, flakes, minced or powder to soup producers, instant noodle manufacturers, seasoning blenders and food service distributors.',
        'features'          => ['High Solids Onion Varieties', 'Uniform Slice Thickness', 'Strong Consistent Flavour', 'Rings, Flakes or Powder'],
        'uses'              => ['Soups & instant noodles', 'Seasoning blends & mixes', 'Processed meat & poultry', 'Food service & catering supply'],
        'origin'            => 'Egypt — Nile Delta Region',
        'form'              => 'Rings / Flakes / Minced / Powder',
    ],
    [
        'name'              => 'Nigella Seeds',
        'slug'              => 'nigella-seeds',
        'category'          => 'spices',
        'image'             => 'spices/lemon.webp',
        'short_description' => 'Black seed with an earthy, slightly bitter flavour and high thymoquinone content. A growing ingredient in health and food markets.',
        'full_description'  => 'Egyptian nigella seeds (black seed / Nigella sativa) are valued for their naturally high thymoquinone content — a bioactive compound with well-documented health properties — as well as their distinctive earthy, slightly bitter, oregano-like flavour. Cleaned and sorted to export grade, our nigella supplies health supplement manufacturers, bakeries, spice blenders and pharmaceutical ingredient buyers.',
        'features'          => ['High Thymoquinone Content', 'Earthy Distinctive Flavour', 'Carefully Sorted & Cleaned', 'Supplement & Food Grade'],
        'uses'              => ['Health supplements & black seed oil', 'Bread & bakery topping', 'Spice blends', 'Pharmaceutical ingredient'],
        'origin'            => 'Egypt',
        'form'              => 'Whole Seeds / Cold-Press Oil Grade',
    ],
    [
        'name'              => 'Dried Yellow Lemon',
        'slug'              => 'dried-yellow-lemon',
        'category'          => 'spices',
        'image'             => 'spices/dried_yallow_lemon .webp',
        'short_description' => 'Bright, tangy dried yellow lemon slices and powder with natural citrus flavour. Used in beverages, marinades and seasoning blends.',
        'full_description'  => 'Dried yellow lemon is produced from fresh lemons that are sliced or halved and carefully dehydrated to concentrate their natural citric acid and citrus aroma. Supplied as slices, rings or ground powder, our dried yellow lemon is used by beverage manufacturers for herbal teas, spice blenders for marinades and seasoning producers for natural citrus flavouring.',
        'features'          => ['Natural Citric Acid Concentration', 'Bright Citrus Aroma', 'Slices, Rings or Powder', 'No Artificial Additives'],
        'uses'              => ['Herbal & detox tea blends', 'Marinades & salad dressings', 'Seasoning blends', 'Natural flavouring ingredient'],
        'origin'            => 'Egypt',
        'form'              => 'Slices / Rings / Powder',
    ],
    [
        'name'              => 'Paprika',
        'slug'              => 'paprika',
        'category'          => 'spices',
        'image'             => 'spices/paprika.webp',
        'short_description' => 'Vibrant red paprika with high ASTA colour value and sweet-to-mild heat. Supplied to food manufacturers for colour and flavour.',
        'full_description'  => 'Egyptian paprika is produced from selected red pepper varieties chosen for their high ASTA colour value, natural carotenoid content and balanced sweet-to-mild flavour profile. Dried, cleaned and milled to consistent particle size, our paprika supplies food processors, meat manufacturers, spice blenders and natural colouring companies that demand reliable colour performance and clean flavour.',
        'features'          => ['High ASTA Colour Value', 'Natural Carotenoid Content', 'Sweet to Mild Heat Profile', 'Consistent Particle Size'],
        'uses'              => ['Processed meat & sausage colouring', 'Spice blends & rubs', 'Snack food seasoning', 'Natural food colouring'],
        'origin'            => 'Egypt',
        'form'              => 'Ground Powder',
    ],
    [
        'name'              => 'Turmeric',
        'slug'              => 'turmeric',
        'category'          => 'spices',
        'image'             => 'spices/turmeric.webp',
        'short_description' => 'Bright golden turmeric with high curcumin content. A staple in food colouring, nutraceutical and pharmaceutical manufacturing.',
        'full_description'  => 'Egyptian processed turmeric is produced from select finger rhizomes with consistently high curcumin content, delivering the vibrant golden colour and warm, earthy flavour demanded by food, nutraceutical and pharmaceutical buyers. Dried, cleaned and milled to a fine powder under hygienically controlled conditions, our turmeric supplies curry manufacturers, natural colouring companies, health supplement producers and cosmetic ingredient buyers globally.',
        'features'          => ['High Curcumin Content (3%+)', 'Vibrant Golden Colour', 'Food, Pharma & Cosmetic Grade', 'Fine Powder Consistency'],
        'uses'              => ['Curry blends & spice mixes', 'Natural food & beverage colouring', 'Nutraceutical supplements', 'Cosmetic & skincare ingredient'],
        'origin'            => 'Egypt (processed & exported)',
        'form'              => 'Whole Rhizome / Finger / Ground Powder',
    ],

];
